import { Inter } from "next/font/google";
import "./globals.css";
import Header from '/components/Header';




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first Next js app",
  description: "Generated by create app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" 
              href="https://bootswatch.com/5/sandstone/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        <Header />
        <main>
          {children}
        </main>

      </body>
    </html>
  );
}

