import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from '/components/Navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My first Next js app",
  description: "Generated by create app",
};




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" 
              href="https://bootswatch.com/5/sandstone/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        
        <Navigation />
        <div className="container">
          {children}          
        </div>  
      </body>
    </html>
  );
}
